theme: minima
#jekyll-theme-modernist
#jekyll-theme-merlot
#jekyll-theme-cayman
#jekyll-theme-slate
#jekyll-theme-leap-day
#jekyll-theme-midnight



title: Mi Blog
description: Â© 2025 | Bienvenido a mi blog en GitHub Pages usando un tema bonito.


# NavegaciÃ³n personalizada
header_pages:
main:
  - title: "ğŸ  Inicio"
    url: /
  - title: "ğŸ‘¤ Acerca de mÃ­"
    url: /about/
  - title: "ğŸ› ï¸ Proyectos"
    url: /proyectos/
  - title: "ğŸ“¬ Contacto"
    url: /contacto/
